package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"rocket-tickets/model"
	"rocket-tickets/repository"
)

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.Event, error) {
	events, err := r.EventStore.GetEvents()
	if err != nil {
		return nil, err
	}

	items := make([]*model.Event, 0, len(events))
	for i := range events {
		items = append(items, &events[i])
	}

	return items, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id uint) (*model.Event, error) {
	event, err := r.EventStore.GetEvent(id)
	if err != nil {
		if err == repository.ErrEventNotFound {
			return nil, nil
		}
		return nil, err
	}

	return &event, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
